from .LTX2EasyPromptQwen import NODE_CLASS_MAPPINGS as QWEN_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QWEN_DISPLAY_NAME_MAPPINGS
from .LTX2VisionEasyPromptLD import NODE_CLASS_MAPPINGS as VISION_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VISION_DISPLAY_NAME_MAPPINGS
from .LTX2InferenceServerConfig import NODE_CLASS_MAPPINGS as SERVER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SERVER_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**QWEN_MAPPINGS, **VISION_MAPPINGS, **SERVER_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**QWEN_DISPLAY_NAME_MAPPINGS, **VISION_DISPLAY_NAME_MAPPINGS, **SERVER_DISPLAY_NAME_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
